#!/bin/bash

LABEL=$1
ROUTE=$2


COLOR_UP='"#00ff00"'
COLOR_DOWN='"#FF0000"'

if (nmcli | grep "$ROUTE" > /dev/null); then
    echo "<span color=$COLOR_UP>$LABEL</span>";
else
    echo "<span color=$COLOR_DOWN>$LABEL</span>";
fi;
